CREATE FUNCTION fnCalcNumSponsorContacts (@SponsorID INT)
RETURNS INT
AS
BEGIN
	DECLARE @RET INT =
		(SELECT COUNT(SponsorContactID) FROM SPONSOR_CONTACT WHERE SponsorID = @SponsorID)
	RETURN @RET
END
GO
